export const QueryKeys = {
	LIST_MOVIE: "LIST_MOVIE",
	MOVIE_DETAILS: "MOVIE_DETAILS",
	LIST_USER: "LIST_USER",
	TICKET_ROOM: "TICKET_ROOM",
	LIST_CINEMA: "LIST_CINEMA",
	LOGIN: "LOGIN",
	LIST_BANNER: "listBanner",
};
